server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        globally_quoted_identifiers: true

    open-in-view: false

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    username: test_user
    password: GS3ef_fsd^!
    url: jdbc:mysql://localhost:3306/answer_king

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    username: test_user
    password: GS3ef_fsd^!
    url: jdbc:mysql://localhost:3306/answer_king_test
    name: answer_king_test
  sql:
    init:
      mode: never

---

spring:
  config:
    activate:
      on-profile: integration-test

  datasource:
    username:
    password:
    url:
    name:
  sql:
    init:
      mode: never

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    username: test_user
    password: GS3ef_fsd^!
    url: jdbc:mysql://mysqldb:3306/answer_king

---
spring:
  config:
    activate:
      on-profile: production

  datasource:
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}

---
logging:
  pattern:
    dateformat: 'yyyy-MM-dd HH:mm:ss.SSS'
management:
  endpoints:
    jmx:
      exposure:
        include: '*'