DELETE FROM item_category;
DELETE FROM order_item;
DELETE FROM `order`;
DELETE FROM order_status;
DELETE FROM item;
DELETE FROM category;

ALTER TABLE item_category AUTO_INCREMENT = 1;
ALTER TABLE item AUTO_INCREMENT = 1;
ALTER TABLE category AUTO_INCREMENT = 1;
ALTER TABLE `order` AUTO_INCREMENT = 1;
ALTER TABLE order_status AUTO_INCREMENT = 1;